import HowItWorks from './HowItWorks';
import GoogleMark from './GoogleMark';
import './auth-landing.css';
export default function AuthLanding({page,onNavigate,googleAvailable}) {
  const home=()=>{onNavigate('home');window.scrollTo(0,0);};
  return <>
    <header className="public-header"><div className="public-nav"><button className="public-brand" onClick={home}>RenalSync</button><nav aria-label="Public navigation"><button className={page==='home'?'current':''} onClick={home}>Home</button><a href="#how-it-works" className={page==='how-it-works'?'current':''} aria-current={page==='how-it-works'?'page':undefined} onClick={(event)=>{event.preventDefault();onNavigate('how-it-works');}}>How it works</a></nav><div className="public-account"><button onClick={()=>onNavigate('signin')}>Sign in</button><button className="public-primary" onClick={()=>onNavigate('signup')}>Get started</button></div></div></header>
    {page==='how-it-works' ? <HowItWorks onNavigate={onNavigate} /> : page==='home' ? <main className="public-main"><section className="public-hero"><p className="public-eyebrow">Food tracking that fits your everyday life</p><h1>A clearer picture<br />of your plate.</h1><p className="public-hero-copy">RenalSync helps you record what you eat, understand your nutrients, and share your food history with your dietitian. Start with your voice. Review before you save.</p><div className="public-hero-actions"><button className="public-primary" onClick={()=>onNavigate('signup')}>Sign up</button><button className="public-secondary google-signin" disabled={!googleAvailable} onClick={()=>onNavigate('google')}><GoogleMark />Sign up with Google</button></div><p className="public-disclosure">{!googleAvailable && <>Google sign-in is being set up. Email sign-up is available.<br /></>}Your microphone stays off until you start it. You choose when to share your record.</p></section><section className="public-features" id="daily-routine"><h2>A simpler way to keep track.</h2><div><article><span>01</span><h3>Say what you ate.</h3><p>Use voice assistance or enter a meal yourself. Review the food and portion before saving.</p></article><article><span>02</span><h3>See the details.</h3><p>Explore recipes and follow the nutrients you choose. Missing information stays clearly marked.</p></article><article><span>03</span><h3>Bring your care team in.</h3><p>Save a snapshot of your record and grant your dietitian read access when you are ready.</p></article></div></section></main> : <div className="public-auth-heading"><h1>{page==='care-invite'?'Review your care invitation':page==='rd-signin'?'Dietitian sign in':'Continue to RenalSync'}</h1><p>{page==='care-invite'?'Sign in with the exact email that received the invitation. Nothing is shared until you accept.':page==='rd-signin'?'Review the food records your patients share with you.':'Keep your food log, recipes, and nutrition history together.'}</p></div>}
    {['home','how-it-works'].includes(page)&&<footer className="public-footer"><span>RenalSync</span><a href="#rd-signin" onClick={e=>{e.preventDefault();onNavigate('rd-signin');}}>For dietitians <span aria-hidden="true">→</span></a></footer>}
  </>;
}
