import {useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';
import {UserPlus,Mail,QrCode,Copy,Check,Clock,ShieldCheck,X,Users} from 'lucide-react';
import './care-invitations.css';
const KEY='renalsync-care-invitation';
export function captureCareInvitation(){
 const id=window.location.hash.match(/^#care-invite\/([0-9a-f-]{36})$/i)?.[1];
 try{if(id)sessionStorage.setItem(KEY,id);return id||sessionStorage.getItem(KEY);}catch{return id;}
}
const statusLabel=i=>i.status==='accepted'?(i.active?'Connected':'Access removed'):i.status==='pending'?'Awaiting acceptance':i.status[0].toUpperCase()+i.status.slice(1);
export default function CareInvitations({client,account,isRD,onChanged,onConnections}){
 const [rows,setRows]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [formOpen,setFormOpen]=useState(false),[email,setEmail]=useState(''),[patientName,setPatientName]=useState(''),[readerName,setReaderName]=useState('');
 const [selected,setSelected]=useState(null),[qr,setQr]=useState(''),[consent,setConsent]=useState(false),[linkId,setLinkId]=useState(captureCareInvitation);
 const [linkedInvitation,setLinkedInvitation]=useState(null),[linkLoading,setLinkLoading]=useState(false); const alive=useRef(true),working=useRef(false);
 const link=selected?`${window.location.origin}/#care-invite/${selected.id}`:'';
 async function refresh(){const r=await client.invitations();if(alive.current){setRows(Array.isArray(r)?r:[]);onConnections?.(Array.isArray(r)?r:[]);}}
 useEffect(()=>{alive.current=true;let active=true;const load=async()=>{try{const r=await client.invitations();if(active){setRows(Array.isArray(r)?r:[]);onConnections?.(Array.isArray(r)?r:[]);setError('');}}catch(e){if(active)setError(e.message);}finally{if(active)setLoading(false);}};load();const timer=setInterval(load,15000);return()=>{active=false;alive.current=false;clearInterval(timer);};},[client,account.id]);
 useEffect(()=>{const update=()=>setLinkId(captureCareInvitation());window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{let active=true;setQr('');if(link)QRCode.toDataURL(link,{width:240,margin:4,errorCorrectionLevel:'M',color:{dark:'#132a50',light:'#ffffff'}}).then(data=>{if(active)setQr(data);}).catch(()=>{if(active)setError('QR code could not be created. Copy the link instead.');});return()=>{active=false;};},[link]);
 async function act(fn){if(working.current)return;working.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(alive.current)setError(e.message||'Please try again.');}finally{working.current=false;if(alive.current)setBusy(false);}}
 useEffect(()=>{let active=true;setLinkedInvitation(null);if(!linkId){setLinkLoading(false);return;}setLinkLoading(true);client.invitations('get',{id:linkId}).then(inv=>{if(active&&inv?.id===linkId)setLinkedInvitation(inv);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLinkLoading(false);});return()=>{active=false;};},[client,account.id,linkId]); const outgoing=rows.filter(i=>i.reader_id===account.id),incoming=rows.filter(i=>i.reader_id!==account.id&&i.status==='pending');
 const highlighted=rows.find(i=>i.id===linkId&&i.reader_id!==account.id)||(linkedInvitation?.id===linkId&&linkedInvitation.reader_id!==account.id?linkedInvitation:null);
 const toReview=highlighted?[highlighted,...incoming.filter(i=>i.id!==highlighted.id)]:incoming;
 function dismissLink(){try{sessionStorage.removeItem(KEY);}catch{}setLinkId(null);if(window.location.hash.startsWith('#care-invite/'))window.history.replaceState(null,'',window.location.pathname);}
 async function respond(inv,action){await client.invitations(action,{id:inv.id,consent:action==='accept'});await refresh();setConsent(false);dismissLink();setNotice(action==='accept'?'Connected. Your dietitian can now read your saved record and future updates.':'Invitation declined. No new access was granted.');onChanged?.();}
 return <section className="care-invitations" aria-label={isRD?'Patient invitations':'Care invitations'}>
  {isRD&&<><div className="invitation-toolbar"><div><span className="invitation-eyebrow">CARE CONNECTIONS</span><h3>Your patient network</h3><p>Invite by email. Records become available after the patient accepts.</p></div><button className="invite-primary" onClick={()=>setFormOpen(!formOpen)} aria-expanded={formOpen}><UserPlus size={18}/>Add patient</button></div>
  <div className="invitation-stats"><div><Users size={20}/><span><strong>{outgoing.filter(i=>i.status==='accepted'&&i.active).length}</strong> Accepted connections</span></div><div><Clock size={20}/><span><strong>{outgoing.filter(i=>i.status==='pending').length}</strong> Awaiting acceptance</span></div><div><ShieldCheck size={20}/><span>Patient-controlled access<small>Consent is required before sharing</small></span></div></div>
  {formOpen&&<form className="invite-form" onSubmit={e=>{e.preventDefault();act(async()=>{const inv=await client.invitations('create',{email:email.trim(),readerName:readerName.trim(),patientName:patientName.trim()});if(!alive.current)return;setSelected(inv);setFormOpen(false);await refresh();setNotice('Invitation created. No email has been sent yet.');});}}><div className="invite-form-heading"><h4>Invite a patient</h4><button type="button" aria-label="Close invite form" onClick={()=>setFormOpen(false)}><X size={18}/></button></div><label>Your name as the patient knows you<input required maxLength={100} value={readerName} onChange={e=>setReaderName(e.target.value)} placeholder="e.g. Jane Smith" autoComplete="name"/></label><label>Patient’s exact email<input type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="patient@example.com"/></label><label>Patient name (optional)<input maxLength={100} value={patientName} onChange={e=>setPatientName(e.target.value)} /></label><p className="invite-caption">They must sign in with this verified email and confirm that you are their dietitian. Your account email, {account.email || 'not verified'}, will be shown to them.</p><button className="invite-primary" disabled={busy}>Create invitation</button></form>}
  {selected&&<div className="invite-share"><div><h4>Invitation ready</h4><p className="invite-recipient"><Mail size={17}/>{selected.recipient_email}</p><p>Send the email or let this patient scan the QR code. Both require the same email and explicit acceptance.</p><div className="invite-share-actions"><button className="invite-primary" disabled={busy} onClick={()=>act(async()=>{const r=await client.sendInvitationEmail(selected.id);if(alive.current)setNotice(r.message);await refresh();})}><Mail size={17}/>Send invitation email</button><button disabled={busy} onClick={()=>act(async()=>{await navigator.clipboard.writeText(link);setNotice('Invitation link copied.');})}><Copy size={16}/>Copy link</button><button onClick={()=>setSelected(null)} aria-label="Close invitation sharing"><X size={17}/></button></div><label>Invitation link<input readOnly value={link} onFocus={e=>e.target.select()}/></label><small>Expires {new Date(selected.expires_at).toLocaleDateString()}. Creating a QR code does not share any records.</small></div><div className="invite-qr">{qr?<img src={qr} alt="QR code for this email-specific patient invitation" width="200" height="200"/>:<span>Preparing QR code…</span>}<span><QrCode size={16}/>Scan to review invitation</span></div></div>}
  {outgoing.length>0&&<details className="invitation-history" open><summary>Invitations <span>{outgoing.length}</span></summary><div className="invite-table-scroll"><table><thead><tr><th>Patient / email</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{outgoing.map(i=><tr key={i.id}><td><strong>{i.patient_name||'Name not provided'}</strong><small>{i.recipient_email}</small></td><td><span className={`invite-badge ${i.status}`}>{statusLabel(i)}</span></td><td>{new Date(i.created_at).toLocaleDateString()}</td><td>{i.status==='pending'&&<div className="invite-row-actions"><button onClick={()=>setSelected(i)} disabled={busy}>Email / QR</button><button disabled={busy} onClick={()=>act(async()=>{await client.invitations('cancel',{id:i.id});if(selected?.id===i.id)setSelected(null);await refresh();})}>Cancel</button></div>}{i.status==='accepted'&&i.active&&<small>{i.owner_id?'Patient linked · open their saved file below':'Connected'}</small>}</td></tr>)}</tbody></table></div></details>}
  </>}
  {!isRD&&toReview.map(inv=><article className="patient-invite" key={inv.id}><span className="invitation-eyebrow">CARE INVITATION</span><h3>{inv.reader_name} would like to connect</h3><p><strong>{inv.reader_email}</strong></p><p>This name is provided by the inviter. Confirm that this is your dietitian before accepting.</p>{inv.status==='pending'?<><div className="invite-consent-copy"><h4>What you will share</h4><p>Your nutrition profile, saved foods, portions, meal times, nutrient information, and saved conversation text—including future updates. Audio is not shared. You can revoke access in Account & care sharing.</p></div><label className="invite-consent"><input type="checkbox" checked={consent===inv.id} onChange={e=>setConsent(e.target.checked?inv.id:false)}/>I recognize this dietitian and agree to share my record.</label><div className="invite-share-actions"><button className="invite-primary" disabled={busy||consent!==inv.id} onClick={()=>act(()=>respond(inv,'accept'))}><Check size={18}/>Accept & connect</button><button disabled={busy} onClick={()=>act(()=>respond(inv,'decline'))}>Decline</button></div></>:<><p>{statusLabel(inv)}</p><button onClick={dismissLink}>Dismiss</button></>}</article>)}
  {!isRD&&linkId&&!highlighted&&!loading&&!linkLoading&&<div className="patient-invite"><h3>Check your invitation email</h3><p>This invitation is not available to this account. Sign in with the exact email it was sent to, or ask your dietitian for a new invitation.</p><button onClick={dismissLink}>Dismiss</button></div>}
  {loading&&<p className="invite-caption" role="status">Checking care invitations…</p>}
  {error&&<p className="invite-error" role="alert">{error}</p>}{notice&&<p className="invite-notice" role="status">{notice}</p>}
 </section>;
}
